package models.business.enums;

public enum Endpoint {
  GET_TASKS,
  GET_SUBTASKS,
  GET_EPICS,
  POST_TASK,
  POST_SUBTASK,
  POST_EPIC,
  GET_HISTORY,
  DELETE_TASKS,
  DELETE_EPICS,
  GET_TASK_BY_ID,
  GET_PRIORITIZED_TASK,
  DELETE_TASK_BY_ID,
  GET_EPIC_BY_ID,
  DELETE_EPIC_BY_ID,
  GET_SUBTASK_BY_ID,
  DELETE_SUBTASK_BY_ID,
  GET_SUBTASK_IN_EPIC,
  DELETE_SUBTASKS_IN_EPIC,
  UNKNOWN
}
